use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :flexphoenix, Flexphoenix.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [host: "ec2-54-254-197-242.ap-southeast-1.compute.amazonaws.com", port: {:system, "PORT"} ],
  cache_static_manifest: "priv/static/manifest.json",
  server: true

# Do not print debug messages in production
config :logger, level: :info

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :flexphoenix, Flexphoenix.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [port: 443,
#               keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#               certfile: System.get_env("SOME_APP_SSL_CERT_PATH")]
#
# Where those two env variables return an absolute path to
# the key and cert in disk or a relative path inside priv,
# for example "priv/ssl/server.key".
#
# We also recommend setting `force_ssl`, ensuring no data is
# ever sent via http, always redirecting to https:
#
#     config :flexphoenix, Flexphoenix.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# ## Using releases
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
#
#     config :phoenix, :serve_endpoints, true
#
# Alternatively, you can configure exactly which server to
# start per endpoint:
#
#     config :flexphoenix, Flexphoenix.Endpoint, server: true
#
# You will also need to set the application root to `.` in order
# for the new static assets to be served after a hot upgrade:
#
#     config :flexphoenix, Flexphoenix.Endpoint, root: "."

# Configure your database
config :flexphoenix, Flexphoenix.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: System.get_env("POSTGRES_USERNAME"),
  password: System.get_env("POSTGRES_PASSWORD"),
  database: "flexphoenix_dev",
  hostname: "localhost",
  pool_size: 10

config :flexphoenix, ecto_repos: [Flexphoenix.Repo]

config :arc,
	storage: Arc.Storage.S3,
  bucket: {:system, "FLEX_AWS_S3_BUCKET"},
	asset_host: System.get_env("FLEX_AWS_S3_ENDPOINT")

config :ex_aws,
  virtual_host: true,
  access_key_id: [{:system, "FLEX_AWS_ACCESS_KEY_ID"}, :instance_role],
  secret_access_key: [{:system, "FLEX_AWS_SECRET_ACCESS_KEY"}, :instance_role],
  region: "ap-southeast-1"#,

# Finally import the config/prod.secret.exs
# which should be versioned separately.

import_config "prod.secret.exs"
